services:
  - type: web
    name: django-polls
    env: docker
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: polls-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: "*" # Change this to your domain later

databases:
  - name: polls-db
    plan: free
